List<String> genresN = [
    'Documentaries',
    'International TV Shows',
    'TV Dramas',
    'TV Mysteries',
    'Crime TV Shows',
    'TV Action & Adventure',
    'Docuseries',
    'Reality TV',
    'Romantic TV Shows',
    'TV Comedies',
    'TV Horror',
    'Children & Family Movies',
    'Dramas',
    'Independent Movies',
    'International Movies',
    'British TV Shows',
    'Spanish-Language TV Shows',
    'Thrillers',
    'Music & Musicals',
    'Horror Movies',
    'Sci-Fi & Fantasy',
    'Kids\' TV',
    'Classic Movies',
    'Anime Features',
    'Action & Adventure',
    'Stand-Up Comedy & Talk Shows',
    'Korean TV Shows',
    'Science & Nature TV',
    'LGBTQ Movies',
    'Cult Movies',
    'Sports Movies',
    'Faith & Spirituality'
  ];

  List<String> genresD = [
    'Animation',
    'Family',
    'Comedy',
    'Musical',
    'Docuseries',
    'Historical',
    'Music',
    'Biographical',
    'Documentary',
    'Action-Adventure',
    'Superhero',
    'Reality',
    'Survival',
    'Animals & Nature',
    'Kids',
    'Coming of Age',
    'Drama',
    'Fantasy',
    'Crime',
    'Science Fiction',
    'Lifestyle',
    'Romance',
    'Dance',
    'Police/Cop',
    'Anthology',
    'Spy/Espionage',
    'Western',
    'Medical',
    'Anime',
    'Talk Show',
    'Buddy',
    'Game Show / Competition',
    'Sports',
    'Variety',
    'Parody',
    'Soap Opera / Melodrama',
    'Mystery',
    'Concert Film',
    'Romantic Comedy',
    'Thriller',
];

List<String> genresA = [
'Action',
'Drama',
'Comedy',
'Sports',
'Unscripted',
'Kids',
'Documentary',
'Special Interest',
'Suspense',
'Animation',
'Western',
'Arts, Entertainment and Culture',
'LGBTQ',
'Romance',
'Horror',
'Science Fiction',
'Faith and Spirituality',
'Anime',
'Adventure',
'Arthouse',
'International',
'Music Videos and Concerts',
'Talk Show and Variety',
'Fantasy',
'Military and War',
'Historical',
];

List<String> genresH = [
  'Fantasy',
  'Family',
  'Drama',
  'Romance',
  'War',
  'Thriller',
  'Crime',
  'History',
  'Animation',
  'Comedy',
  'Action',
  'Western',
  'Music',
  'Horror',
  'Documentary',
  'Sci-Fi',
  'Sport',
  'Documentation',
  'European',
  'Reality',
];

List<String> genresI = [
  'Drama',
  'Crime',
  'Action',
  'Adventure',
  'Biography',
  'History',
  'Sci-Fi',
  'Romance',
  'Western',
  'Comedy',
  'Thriller',
  'Animation',
  'Family',
  'War',
  'Fantasy',
  'Mystery',
  'Music',
  'Film-Noir',
  'Musical',
  'Sport',
  'Horror',
];


  Map<String, String> genreImagesN = {
    'Documentaries': 'assets/documental.jpeg',
    'International TV Shows': 'assets/international.jpeg',
    'TV Dramas': 'assets/drama.jpeg',
    'TV Mysteries': 'assets/misterio.jpeg',
    'Crime TV Shows': 'assets/crimen.jpeg',
    'TV Action & Adventure': 'assets/accion.jpeg',
    'Docuseries': 'assets/docuserie.jpeg',
    'Reality TV': 'assets/reality.jpeg',
    'Romantic TV Shows': 'assets/romance.jpeg',
    'TV Comedies': 'assets/comedia.jpeg',
    'TV Horror': 'assets/terror.jpeg',
    'Children & Family Movies': 'assets/familia.jpeg',
    'Dramas': 'assets/dramadrama.jpeg',
    'Independent Movies': 'assets/mala.jpeg',
    'International Movies': 'assets/internacionalinternacional.jpeg',
    'British TV Shows': 'assets/british.jpeg',
    'Spanish-Language TV Shows': 'assets/españa.jpeg',
    'Thrillers': 'assets/thriller.jpeg',
    'Music & Musicals': 'assets/musical.jpeg',
    'Horror Movies': 'assets/horror.jpeg',
    'Sci-Fi & Fantasy': 'assets/cienciaficcion.jpeg',
    'Kids\' TV': 'assets/kids.jpeg',
    'Classic Movies': 'assets/clasico.jpeg',
    'Anime Features': 'assets/anime.jpeg',
    'Action & Adventure': 'assets/accion.jpeg',
    'Stand-Up Comedy & Talk Shows': 'assets/talk.jpeg',
    'Korean TV Shows': 'assets/korea.jpeg',
    'Science & Nature TV': 'assets/naturaleza.jpeg',
    'LGBTQ Movies': 'assets/lgbt.jpeg',
    'Cult Movies': 'assets/cult.jpeg',
    'Sports Movies': 'assets/sport.jpeg',
    'Faith & Spirituality': 'assets/espiritual.jpeg',
    'default': 'assets/logo.webp',
  };

  Map<String, String> genreImagesD ={
    'Movie': 'assets/movie.jpeg',
    'TV Show': 'assets/tvShow.jpeg',
    'Animation':'assets/familia.jpeg',
    'Family':'assets/familia.jpeg',
    'Comedy':'assets/comedia.jpeg',
    'Musical':'assets/musical.jpeg',
    'Docuseries':'assets/docuserie.jpeg',
    'Historical':'assets/espiritual.jpeg', //
    'Music':'assets/espiritual.jpeg',
    'Biographical':'assets/docuserie.jpeg',
    'Documentary':'assets/documental.jpeg',
    'Action-Adventure':'assets/accion.jpeg',
    'Superhero':'assets/espiritual.jpeg', //
    'Reality':'assets/reality.jpeg',
    'Survival':'assets/espiritual.jpeg', //
    'Animals & Nature':'assets/naturaleza.jpeg',
    'Kids':'assets/kids.jpeg',
    'Coming of Age':'assets/espiritual.jpeg', //
    'Drama':'assets/drama.jpeg',
    'Fantasy':'assets/espiritual.jpeg', //
    'Crime':'assets/crimen.jpeg',
    'Science Fiction':'assets/cienciaficcion.jpeg',
    'Lifestyle':'assets/espiritual.jpeg', //
    'Romance':'assets/espiritual.jpeg',
    'Dance':'assets/espiritual.jpeg', //
    'Police/Cop':'assets/espiritual.jpeg',
    'Anthology':'assets/espiritual.jpeg', //
    'Spy/Espionage':'assets/espiritual.jpeg', //
    'Western':'assets/espiritual.jpeg', //
    'Medical':'assets/espiritual.jpeg', //
    'Anime':'assets/anime.jpeg',
    'Talk Show':'assets/talk.jpeg',
    'Buddy':'assets/espiritual.jpeg',
    'Game Show / Competition':'assets/espiritual.jpeg',
    'Sports':'assets/sport.jpeg',
    'Variety':'assets/espiritual.jpeg', //
    'Parody':'assets/espiritual.jpeg', //
    'Soap Opera / Melodrama':'assets/espiritual.jpeg', //
    'Mystery':'assets/misterio.jpeg',
    'Concert Film':'assets/espiritual.jpeg', //
    'Romantic Comedy':'assets/romance.jpeg',
    'Thriller':'assets/thriller.jpeg',
    'default': 'assets/logo.webp',
  };

  Map<String, String> genreImagesA ={
    'Comedy':'assets/musical.jpeg',
    'Drama':'assets/musical.jpeg',
    'International':'assets/musical.jpeg',
    'Action':'assets/musical.jpeg',
    'Suspense':'assets/musical.jpeg',
    'Documentary':'assets/musical.jpeg',
    'Fantasy':'assets/musical.jpeg',
    'Kids':'assets/musical.jpeg',
    'Special Interest':'assets/musical.jpeg',
    'Science Fiction':'assets/musical.jpeg',
    'Adventure':'assets/musical.jpeg',
    'Horror':'assets/musical.jpeg',
    'Sports':'assets/musical.jpeg',
    'Talk Show and Variety':'assets/musical.jpeg',
    'Anime':'assets/musical.jpeg',
    'Animation':'assets/musical.jpeg',
    'Music Videos and Concerts':'assets/musical.jpeg',
    'Faith and Spirituality':'assets/musical.jpeg',
    'Military and War':'assets/musical.jpeg',
    'Western':'assets/musical.jpeg',
    'Romance':'assets/musical.jpeg',
    'LGBTQ':'assets/musical.jpeg',
    'Unscripted':'assets/musical.jpeg',
    'Arthouse':'assets/musical.jpeg',
    'Historical':'assets/musical.jpeg',
    'default': 'assets/logo.webp',
  };

   Map<String, String> genreImagesH = {
    'Fantasy':'assets/misterio.jpeg',
    'Family':'assets/misterio.jpeg',
    'Drama':'assets/misterio.jpeg',
    'Romance':'assets/misterio.jpeg',
    'War':'assets/misterio.jpeg',
    'Thriller':'assets/misterio.jpeg',
    'Crime':'assets/misterio.jpeg',
    'History':'assets/misterio.jpeg',
    'Animation':'assets/misterio.jpeg',
    'Comedy':'assets/misterio.jpeg',
    'Action':'assets/misterio.jpeg',
    'Western':'assets/misterio.jpeg',
    'Music':'assets/misterio.jpeg',
    'Horror':'assets/misterio.jpeg',
    'Documentary':'assets/misterio.jpeg',
    'Sci-Fi':'assets/misterio.jpeg',
    'Sport':'assets/misterio.jpeg',
    'Documentation':'assets/misterio.jpeg',
    'European':'assets/misterio.jpeg',
    'Reality':'assets/misterio.jpeg',
    'default': 'assets/logo.webp',
  };

  Map<String, String> genreImagesI ={
    'Drama': 'assets/drama.jpeg',
    'Crime': 'assets/crimen.jpeg',
    'Action': 'assets/accion.jpeg',
    'Adventure': 'assets/misterio.jpeg', //
    'Biography': 'assets/docuserie.jpeg',
    'History': 'assets/misterio.jpeg', //
    'Sci-Fi': 'assets/cienciaficcion.jpeg',
    'Romance': 'assets/romance.jpeg',
    'Western': 'assets/misterio.jpeg',
    'Comedy': 'assets/comedia.jpeg',
    'Thriller': 'assets/thriller.jpeg',
    'Animation': 'assets/misterio.jpeg',
    'Family': 'assets/familia.jpeg',
    'War': 'assets/misterio.jpeg',
    'Fantasy': 'assets/misterio.jpeg',
    'Mystery': 'assets/misterio.jpeg',
    'Music': 'assets/misterio.jpeg',
    'Film-Noir': 'assets/misterio.jpeg',
    'Musical': 'assets/musical.jpeg',
    'Sport': 'assets/sport.jpeg',
    'Horror': 'assets/horror.jpeg',
  };
